creation_rules:
  # Using a single-key group to be able to use per-key comments,
  # see https://github.com/getsops/sops/issues/845#issuecomment-1364109772
  - key_groups:
    - age:
      - age15fyxdwmg5mvldtqqus87xspuws2u0cpvwheehrtvkexj4tnsqqysw6re2x # jacques
      - age1lj633f3hmscvy0nsewqej8k3jrk9wkhrgw4lafx0p9748ncvjs3qkvdd3d # github
