name: Create and publish a Docker image for latest

on:
  workflow_dispatch:
  schedule:
    - cron: 0 5 * * *

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  docker-build-generic:
    uses: ./.github/workflows/docker-build-template.yaml
    with:
      grist_version: latest
      docker_tag: latest
      target: generic

  docker-build-custom:
    uses: ./.github/workflows/docker-build-template.yaml
    needs: docker-build-generic
    strategy:
      matrix:
        build_env: [DINUM, ANCT]
    with:
      grist_version: latest
      docker_tag: latest-${{ matrix.build_env }}

