name: Create and publish a Docker image for tags

on:
  push:
    tags: ['*']

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  docker-build-generic:
    uses: ./.github/workflows/docker-build-template.yaml
    with:
      docker_tag: ${{ github.ref_name }}
      target: generic
      push_docker_hub: true
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  docker-build-custom:
    uses: ./.github/workflows/docker-build-template.yaml
    needs: docker-build-generic
    strategy:
      matrix:
        build_env: [DINUM, ANCT]
    with:
      docker_tag: ${{ github.ref_name }}-${{ matrix.build_env }}
      build_env: ${{ matrix.build_env }}

