name: Create and publish a Docker image for tags

on:
  push:
    tags: ['*']

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  docker-build-generic:
    uses: ./.github/workflows/docker-build-template.yaml
    with:
      docker_tag: ${{ github.ref_name }}
      target: generic
      push_docker_hub: true
    secrets:
      docker_hub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  docker-build-custom:
    uses: ./.github/workflows/docker-build-template.yaml
    needs: docker-build-generic
    strategy:
      matrix:
        build_env: [DINUM, ANCT]
    with:
      docker_tag: ${{ github.ref_name }}-${{ matrix.build_env }}
      build_env: ${{ matrix.build_env }}

  security-scan:
    runs-on: ubuntu-latest
    needs: docker-build-generic
    # Least access: remove as much permissions as possible
    permissions:
      contents: none
      packages: none
      attestations: none
      id-token: none
    steps:
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@v0.36.0
      with:
        image-ref: 'ghcr.io/gristgouv/grist:${{ github.ref_name }}'
        format: 'table'
        exit-code: '1'
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
